kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: argo-tools
nodes:
- role: control-plane
  extraPortMappings:
  # localhost.run proxy
  - containerPort: 32042
    hostPort: 32042
  # Hubble relay
  - containerPort: 31234
    hostPort: 31234
  # Hubble UI
  - containerPort: 31235
    hostPort: 31235
  extraMounts:
  - hostPath: /var/cilium/images
    containerPath: /opt/images
- role: worker
  extraMounts:
  - hostPath: /var/cilium/images
    containerPath: /opt/images
- role: worker
  extraMounts:
  - hostPath: /var/cilium/images
    containerPath: /opt/images
networking:
  disableDefaultCNI: true