apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: development
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Development Project
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  destinations:
  # Allow deployment to any namespace
  - namespace: '*'
    server: https://kubernetes.default.svc
  # Allow any cluster resource
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  # Allow any namespace resource
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: production
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Production Project
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  destinations:
  # Allow deployment to any namespace
  - namespace: '*'
    server: https://kubernetes.default.svc
  # Allow any cluster resource
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  # Allow any namespace resource
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'